import type { Metadata } from "next";
import "./globals.css";

import BubbleMenu from "@/components/ui/bubble-menu";
import { ThemeProvider } from "@/components/ui/theme-provider";
import HeroBackground3DFull from "@/components/ui/bg";
import LeftSidebar from "@/components/ui/left-sidebar";
import ClientWrapper from "./sections/them-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-background text-foreground">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Background must be OUTSIDE any scroll/transforming containers */}
          <HeroBackground3DFull />

          <ClientWrapper>
            <div className="relative max-w-5xl mx-auto px-4">
              {/* Floating UI */}
              <BubbleMenu />

              {/* Main content (scroll container lives within pages) */}
              {children}
                              <LeftSidebar />
            </div>
          </ClientWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
